services:
  mysql:
    container_name: 'customerconnect-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customerconnectdb'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3307:3306'
